require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 100
  IgnoredPatterns: ['\A\s*#']

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
